# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c5ba11748e8f8b419cfdede53ea061dba9fca5fc852398ad66cda9fcd178d9930941100bec95e84fb9abd5d5aae13cb8900bb7ba0358b9aa5f17b4344de7fff

test:
  secret_key_base: 39daa7e95aec2df8a7553e5d73a7c086069c82ae0a2f1d96fa548df32c0ebb1ac34e66d862938d94c67d5d1506dcfa134cce692d62ebcadd7a6bdc26eb4cb8b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
